# Generated by Django 5.0.14 on 2025-11-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_norm', models.CharField(db_index=True, editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Andar',
                'verbose_name_plural': 'Andares',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_norm', models.CharField(db_index=True, editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_norm', models.CharField(db_index=True, editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_norm', models.CharField(db_index=True, editable=False, max_length=160)),
                ('especialidade', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfissionalParametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_nc', models.IntegerField()),
                ('t_nc', models.IntegerField()),
                ('n_ret', models.IntegerField()),
                ('t_ret', models.IntegerField()),
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medflow.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('andar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medflow.andar')),
                ('funcao', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='medflow.funcionalidade', verbose_name='Funcionalidade')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(default='2025-01-01')),
                ('horario_inicio', models.TimeField()),
                ('horario_final', models.TimeField(editable=False)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medflow.profissional')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medflow.sala')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalDiasAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Seg'), ('TER', 'Ter'), ('QUA', 'Qua'), ('QUI', 'Qui'), ('SEX', 'Sex'), ('SAB', 'Sab'), ('DOM', 'Dom')], max_length=3)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='ProfissionalEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.equipamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'equipamento')},
            },
        ),
        migrations.CreateModel(
            name='SalaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.equipamento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.sala')),
            ],
            options={
                'unique_together': {('sala', 'equipamento')},
            },
        ),
    ]
