# Generated by Django 5.0.14 on 2025-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medflow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfEspecEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medflow.equipamento",
                    ),
                ),
                (
                    "profespec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medflow.profissionalespecialidade",
                    ),
                ),
            ],
            options={
                "unique_together": {("profespec", "equipamento")},
            },
        ),
    ]
