# Generated by Django 5.0.14 on 2025-04-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medflow", "0003_rename_funcao_funcionalidade"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfissionalEspecialidade",
            new_name="Profissional",
        ),
        migrations.RenameModel(
            old_name="ProfEspecEquipamento",
            new_name="ProfissionalEquipamento",
        ),
        migrations.RenameField(
            model_name="profissional",
            old_name="profissional",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="profissionalequipamento",
            old_name="profespec",
            new_name="profissional",
        ),
        migrations.AlterUniqueTogether(
            name="profissional",
            unique_together={("nome", "especialidade")},
        ),
        migrations.AlterUniqueTogether(
            name="profissionalequipamento",
            unique_together={("profissional", "equipamento")},
        ),
    ]
