# Generated by Django 5.0.14 on 2025-04-20 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medflow", "0004_rename_profissionalespecialidade_profissional_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfissionalParametros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_nc", models.IntegerField()),
                ("t_nc", models.IntegerField()),
                ("n_ret", models.IntegerField()),
                ("t_ret", models.IntegerField()),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medflow.profissional",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
