# Generated by Django 5.0.14 on 2025-04-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medflow", "0005_profissionalparametros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissionalparametros",
            name="profissional",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="medflow.profissional"
            ),
        ),
    ]
