# Generated by Django 5.0.14 on 2025-04-21 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medflow", "0006_alter_profissionalparametros_profissional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfissionalDiasAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("SEG", "Seg"),
                            ("TER", "Ter"),
                            ("QUA", "Qua"),
                            ("QUI", "Qui"),
                            ("SEX", "Sex"),
                            ("SAB", "Sab"),
                            ("DOM", "Dom"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medflow.profissional",
                    ),
                ),
            ],
            options={
                "unique_together": {("profissional", "dia_semana")},
            },
        ),
    ]
