# Generated by Django 5.0.14 on 2025-04-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medflow", "0007_profissionaldiasatendimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendamentoSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horario_inicio", models.TimeField()),
                ("horario_final", models.TimeField(editable=False)),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medflow.profissional",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medflow.sala"
                    ),
                ),
            ],
        ),
    ]
