# Generated by Django 5.0.14 on 2025-05-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0008_agendamentosala'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentosala',
            name='data_agendamento',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
